version: '3.3'

services:
  mlflow-server:
    container_name: mlflow-server
    build: .
    image: mlflow-server
    restart: always
    volumes:
      - ./mlruns:/app/mlruns

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "5555:80"
    depends_on:
      - mlflow-server
    restart: always
    links:
      - mlflow-server
    volumes:
      - ./config:/etc/nginx
